version: '3'

services:
  stroy-forum-bot:
    build: .
    container_name: stroy-forum-bot
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
    networks:
      - bot-network
      
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 stroy-forum-bot --cleanup
    environment:
      - TZ=Europe/Moscow
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 